# Generated by Django 5.2.4 on 2025-09-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityInvolvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=100)),
                ('community_link', models.URLField(blank=True, null=True)),
                ('community_logo', models.ImageField(blank=True, null=True, upload_to='community_logos')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Community Involvements',
                'ordering': ['-start_year'],
            },
        ),
    ]
