# Generated by Django 5.2.4 on 2025-09-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_communityinvolvement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('type', models.CharField(choices=[('Presentations', 'Presentations'), ('Articles', 'Articles')], default='Presentations', max_length=20)),
                ('scope', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField()),
                ('published_at', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Content',
                'ordering': ['-published_at'],
            },
        ),
    ]
