# Generated by Django 5.2.4 on 2025-09-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('picture_overview', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('built_for', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('skills', models.ManyToManyField(to='website.skill')),
            ],
            options={
                'verbose_name_plural': 'Professionals Projects',
            },
        ),
    ]
