# Generated by Django 5.2.4 on 2025-09-21 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_professionalproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalproject',
            name='worked_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
